### ISSUE TITLE
Syntax highlighting incorrect for 'once'

### ISSUE THREAD

**Issue by TangerineGameDev** [luckasRanarison/tree-sitter-hypr#5] opened 2023-09-30 19:21 UTC
The animation declaration can use the word 'once'.

![image](https://github.com/luckasRanarison/tree-sitter-hypr/assets/81909104/0f30d240-d225-4006-b483-e8655755d8c7)

Using this plugin it is considered as the boolean 'on', which causes that part to change color...

**Comment by TangerineGameDev** [comment] 2023-09-30 19:29
From what I can see from the code base... This might honestly be hard to fix, as everything is a query...
Theoretically one could create maybe an another query, that are blacklisted words and put 'once' in there...

Lmk if I can help...

**Comment by luckasRanarison** [comment] 2023-10-01 13:03
Thanks for the report, I've totally forgot keyword extraction. This was the cause of the issue: https://tree-sitter.github.io/tree-sitter/creating-parsers#keyword-extraction.

It should be fixed now.

**Closed** 2023-10-01 13:16 UTC
Labels: bug
